POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "jj",
  "password": "1"
}



###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "jj",
  "password": "1"
}

###
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGU3ZTFjMmQ1OTg4ODI0ZTQzNTMyM2EiLCJpYXQiOjE2MjU5MDEwNzF9.tkwh3LuQ15DcARCjAWJoVK_yjWkOolbbJ14D5jd7K94

{
  "title": "C",
  "description": "C",
  "url": "C.com",
  "status": "LEARNING"
}

###

GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGU3ZTFjMmQ1OTg4ODI0ZTQzNTMyM2EiLCJpYXQiOjE2MjU5MDEwNzF9.tkwh3LuQ15DcARCjAWJoVK_yjWkOolbbJ14D5jd7K94

###

PUT http://localhost:5000/api/posts/6061c25ac2533d41dcae2b19
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGU3ZTFjMmQ1OTg4ODI0ZTQzNTMyM2EiLCJpYXQiOjE2MjU5MDEwNzF9.tkwh3LuQ15DcARCjAWJoVK_yjWkOolbbJ14D5jd7K94

{
  "title": "Vue",
  "description": "VUEEEEE",
  "url": "https://vuejs.org",
  "status": "LEARNING"
}

###

DELETE http://localhost:5000/api/posts/6061c25ac2533d41dcae2b19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGU3ZTFjMmQ1OTg4ODI0ZTQzNTMyM2EiLCJpYXQiOjE2MjU5MDEwNzF9.tkwh3LuQ15DcARCjAWJoVK_yjWkOolbbJ14D5jd7K94
###

###
POST http://localhost:5000/api/movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGU3ZTFjMmQ1OTg4ODI0ZTQzNTMyM2EiLCJpYXQiOjE2MjY4NTgyMjl9.UOac3wb-7MePSbUqd2PsTvSqh1q124WZXsjuppUPUcM

{
  "title": "D",
  "description": "D",
  "url": "D.com",
  "status": "LEARNING",
  "images": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fbloganchoi.com%2Fsu-khac-nhau-giua-cac-tac-pham-kiem-hiep-nhat-trung-han%2F&psig=AOvVaw23UbFamc2rXhPspr6Bw4HD&ust=1626943495338000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCMjI3_zi8_ECFQAAAAAdAAAAABAD"
}