POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "jimy5",
  "password": "jimy5"
}



###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "jimy1",
  "password": "jimy1"
}