POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "jj",
  "password": "1"
}



###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "",
  "password": "1"
}